import { expect, test } from "@playwright/test";
import { localStateSchema } from "../src/lib/validation";
import { generateWithConfirmedExtras } from "./helpers/meal-generation";

test("pasted pasta meal asks only for missing grams and confirms the generic Philadelphia mapping", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Dal mio pasto", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Che pasto devi mangiare?" })).toBeVisible();
  await page.getByLabel("Pasto previsto dalla dieta", { exact: true }).fill("Pomodori\n90 gr pasta\n80 gr Philadelphia");
  await page.getByRole("button", { name: "Usa questo pasto", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ho riconosciuto il tuo pasto" })).toBeVisible();
  await expect(page.locator(".meal-errors")).toHaveCount(0);
  await expect(page.locator(".meal-review-row")).toHaveCount(3);
  await expect(page.getByLabel("Grammi da confermare Pomodori", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Grammi da confermare Pasta di semola", { exact: true })).toHaveValue("90");
  await expect(page.getByLabel("Grammi da confermare Formaggio spalmabile classico", { exact: true })).toHaveValue("80");
  await expect(page.getByRole("button", { name: "Trasforma il mio pasto", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Conferma il pasto", exact: true }).click();
  await expect(page.locator(".meal-errors")).toContainText("Pomodori: indica i grammi");
  await expect(page.locator(".meal-base-item")).toHaveCount(0);
  await page.getByLabel("Grammi da confermare Pomodori", { exact: true }).fill("150");
  await page.getByRole("button", { name: "Conferma il pasto", exact: true }).click();
  await expect(page.locator(".meal-errors")).toContainText("Conferma l'uso della voce nutrizionale generica");
  await page.getByLabel(/^Confermo il formaggio spalmabile classico/).check();
  await page.getByRole("button", { name: "Conferma il pasto", exact: true }).click();
  await expect(page.locator(".meal-base-item")).toHaveCount(3);
  await expect(page.locator(".meal-review")).toHaveCount(0);
  await expect(page.locator(".meal-extra-check input:checked")).toHaveCount(0);
  await generateWithConfirmedExtras(page);
  await expect(page.locator(".recipe-page")).toBeVisible({ timeout: 60000 });
  await expect(page.locator(".error-notice")).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Pasta vellutata al pomodoro e formaggio spalmabile", exact: true })).toBeVisible();
  await expect(page.getByTestId("meal-extra-kcal")).toHaveText("0 kcal");
  await expect.poll(() => page.evaluate(() => {
    const raw = localStorage.getItem("fit-chef.workspace.v1");
    return raw ? JSON.parse(raw).recipes.length : 0;
  })).toBe(1);
  const state = localStateSchema.parse(await page.evaluate(() => JSON.parse(localStorage.getItem("fit-chef.workspace.v1")!)));
  const recipe = state.recipes[0];
  expect(recipe.ingredients).toHaveLength(3);
  expect(recipe.ingredients.find((item) => item.ingredientId === "pasta")?.grams).toBe(90);
  expect(recipe.ingredients.find((item) => item.ingredientId === "cream-cheese")?.grams).toBe(80);
  expect(recipe.ingredients.find((item) => item.ingredientId === "tomato")?.grams).toBe(150);
  expect(recipe.nutritionPerServing.kcal).toBeCloseTo(536.7);
  expect(recipe.input.targets.kcal).toBeNull();
  expect(recipe.warnings.some((warning) => warning.includes("non i valori ufficiali Philadelphia"))).toBe(true);
  await page.reload();
  await expect(page.locator(".meal-base-item")).toHaveCount(3);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test("editing the source invalidates recognized weights and cannot silently drop an unknown food", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Dal mio pasto", exact: true }).click();
  const text = page.getByLabel("Pasto previsto dalla dieta", { exact: true });
  await text.fill("Pomodori\n90 gr pasta\n80 gr Philadelphia");
  await page.getByRole("button", { name: "Usa questo pasto", exact: true }).click();
  await expect(page.locator(".meal-review")).toBeVisible();
  await text.fill("Pomodori\n90 gr pasta\n80 gr Philadelphia light");
  await expect(page.locator(".meal-review")).toHaveCount(0);
  await page.getByRole("button", { name: "Usa questo pasto", exact: true }).click();
  await expect(page.locator(".meal-errors")).toContainText("Philadelphia light");
  await expect(page.locator(".meal-base-item")).toHaveCount(0);
  await expect(page.locator(".meal-review")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Trasforma il mio pasto", exact: true })).toBeDisabled();
  await text.fill("150 gr pomodori\n90 grammi pasta\n80 gr Philadelphia");
  await page.getByRole("button", { name: "Usa questo pasto", exact: true }).click();
  await expect(page.getByLabel("Grammi da confermare Pomodori", { exact: true })).toHaveValue("150");
  await expect(page.getByLabel(/^Confermo il formaggio spalmabile classico/)).not.toBeChecked();
});
